/**
 * NOTE: 스모크 테스트 — example/ 을 임시 디렉터리에 복사한 뒤 실제 CLI 를 실행해
 * init → setup → mcp(dry-run/실제) → gitignore --check → check 흐름과 산출물을 검증한다.
 * (리포 안의 example/ 은 건드리지 않는다 — 항상 커밋 가능한 깨끗한 상태 유지)
 */
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { after, before, test } from 'node:test';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CLI = path.join(REPO_ROOT, 'bin', 'cli.mjs');

let projectDir;

const aiw = (args, options = {}) =>
  spawnSync(process.execPath, [CLI, ...args], {
    cwd: projectDir,
    encoding: 'utf-8',
    ...options,
  });

const readProject = relPath => fs.readFileSync(path.join(projectDir, relPath), 'utf-8');
const existsInProject = relPath => fs.existsSync(path.join(projectDir, relPath));

before(() => {
  projectDir = fs.mkdtempSync(path.join(os.tmpdir(), 'aiw-smoke-'));
  // NOTE: example/ 복사 (node_modules 제외) — 배포 후 사용 흐름을 재현할 최소 프로젝트
  fs.cpSync(path.join(REPO_ROOT, 'example'), projectDir, {
    recursive: true,
    filter: src => !src.includes('node_modules'),
  });
  spawnSync('git', ['init', '-b', 'main'], { cwd: projectDir, encoding: 'utf-8' });
});

after(() => {
  if (projectDir) fs.rmSync(projectDir, { recursive: true, force: true });
});

test('aiw init --yes 가 .ai-workflow 스캐폴드와 AI.md 를 생성한다', () => {
  const result = aiw(['init', '--yes']);
  assert.equal(result.status, 0, `init 실패:\n${result.stdout}\n${result.stderr}`);

  for (const relPath of [
    '.ai-workflow/config.json',
    '.ai-workflow/mcp.base.json',
    '.ai-workflow/.env.example',
    '.ai-workflow/.env',
    '.ai-workflow/docs/base.md',
    '.ai-workflow/docs/start-task-guide.md',
    '.ai-workflow/docs/pr-review-guide.md',
    '.ai-workflow/logs/.gitkeep',
    '.ai-workflow/tmp/.gitkeep',
    '.ai-workflow/backup/.gitkeep',
    'AI.md',
  ]) {
    assert.ok(existsInProject(relPath), `${relPath} 가 없습니다`);
  }

  // config.json 스키마 (설계 결정 5)
  const config = JSON.parse(readProject('.ai-workflow/config.json'));
  assert.equal(config.baseBranch, 'main');
  assert.deepEqual(config.branchPrefixes, ['feature', 'fix', 'hotfix', 'release', 'chore', 'refactor', 'docs', 'test']);
  assert.equal(config.commitFormat, 'conventional');
  assert.equal(config.ignoreDerived, true);
  assert.ok(config.tools.includes('claude') && config.tools.includes('vscode'));

  // base.md: generated 헤더 + baseBranch 치환 (설계 결정 7)
  const baseDoc = readProject('.ai-workflow/docs/base.md');
  assert.match(baseDoc, /generated by @taeksoolee\/ai-workflow v\d+\.\d+/);
  assert.match(baseDoc, /직접 수정 금지/);
  assert.match(baseDoc, /origin\/main/);
  assert.ok(!baseDoc.includes('{{'), 'base.md 에 미치환 플레이스홀더가 남아 있습니다');

  // AI.md: 제목 다음 첫 줄에서 base.md 강제 참조 (설계 결정 8)
  const aiMd = readProject('AI.md').split('\n');
  assert.match(aiMd[0], /^# /);
  assert.match(aiMd[2], /^> .*\.ai-workflow\/docs\/base\.md/);
  assert.match(readProject('AI.md'), /<!-- PROJECT:/);

  // .env 권한 600
  const mode = fs.statSync(path.join(projectDir, '.ai-workflow', '.env')).mode & 0o777;
  assert.equal(mode, 0o600, `.env 권한이 600 이 아닙니다: ${mode.toString(8)}`);

  // .gitignore 센티널 블록
  const gitignore = readProject('.gitignore');
  assert.ok(gitignore.includes('# >>> ai-workflow >>>'));
  assert.ok(gitignore.includes('# <<< ai-workflow <<<'));
  assert.ok(gitignore.includes('.ai-workflow/.env'));
  assert.ok(gitignore.includes('CLAUDE.md'));
});

test('aiw setup --yes 가 포인터 파일과 스킬 래퍼를 생성한다', () => {
  const result = aiw(['setup', '--yes']);
  assert.equal(result.status, 0, `setup 실패:\n${result.stdout}\n${result.stderr}`);

  // 포인터 파일 (AGENTS.md 는 codex/opencode 공유 — 1회 생성)
  for (const pointer of [
    'CLAUDE.md',
    '.cursorrules',
    '.kiro/steering/guidelines.md',
    '.github/copilot-instructions.md',
    'AGENTS.md',
    '.windsurfrules',
    '.continue/rules/guidelines.md',
    '.traerules',
    'GEMINI.md',
  ]) {
    assert.ok(existsInProject(pointer), `포인터 ${pointer} 가 없습니다`);
  }
  assert.match(readProject('CLAUDE.md'), /AI\.md/);
  assert.match(readProject('CLAUDE.md'), /\.ai-workflow\/docs\/base\.md/);

  // 스킬 래퍼 — frontmatter 스캔 결과 (start-task, pr-review / 둘 다 command 타입)
  for (const wrapper of [
    '.claude/skills/start-task/SKILL.md',
    '.claude/skills/pr-review/SKILL.md',
    '.cursor/commands/start-task.md',
    '.github/prompts/pr-review.prompt.md',
    '.opencode/command/start-task.md',
    '.agents/skills/start-task/SKILL.md',
    '.windsurf/workflows/start-task.md',
    '.continue/prompts/start-task.prompt',
    '.trae/skills/start-task/SKILL.md',
    '.kiro/skills/start-task/SKILL.md',
    '.agent/workflows/start-task.md',
  ]) {
    assert.ok(existsInProject(wrapper), `래퍼 ${wrapper} 가 없습니다`);
  }

  // command 타입 → Claude 는 disable-model-invocation, 본문은 가이드 문서 참조만
  const claudeSkill = readProject('.claude/skills/start-task/SKILL.md');
  assert.match(claudeSkill, /disable-model-invocation: true/);
  assert.match(claudeSkill, /\.ai-workflow\/docs\/start-task-guide\.md/);
});

test('aiw mcp claude --dry-run 은 파일을 쓰지 않고 요약만 출력한다', () => {
  // NOTE: 크리덴셜이 전부 비어 있으면 "생성할 서버 없음" 으로 실패하므로 하나를 채운다.
  fs.appendFileSync(path.join(projectDir, '.ai-workflow', '.env'), '\nMCP_GITHUB_PERSONAL_ACCESS_TOKEN=dummy-token\n');

  const result = aiw(['mcp', 'claude', '--dry-run']);
  assert.equal(result.status, 0, `mcp dry-run 실패:\n${result.stdout}\n${result.stderr}`);
  assert.ok(!existsInProject('.mcp.json'), 'dry-run 인데 .mcp.json 이 생성되었습니다');
  assert.match(result.stdout + result.stderr, /dry-run/);
  assert.match(result.stdout, /포함된 서버.*github/); // 포함된 서버 보고
  assert.match(result.stderr, /서버 제외/); // 빈 크리덴셜 서버 제외 보고
});

test('aiw mcp claude --yes 가 .mcp.json 을 권한 600 으로 생성한다', () => {
  const result = aiw(['mcp', 'claude', '--yes']);
  assert.equal(result.status, 0, `mcp 실패:\n${result.stdout}\n${result.stderr}`);
  assert.ok(existsInProject('.mcp.json'));

  const mode = fs.statSync(path.join(projectDir, '.mcp.json')).mode & 0o777;
  assert.equal(mode, 0o600);

  const parsed = JSON.parse(readProject('.mcp.json'));
  assert.ok(parsed.mcpServers.github, 'github 서버가 포함되어야 합니다');
  assert.equal(parsed.mcpServers.github.headers.Authorization, 'Bearer dummy-token');
  assert.ok(!parsed.mcpServers['figma-developer-mcp'], '빈 크리덴셜 서버는 제외되어야 합니다');
  assert.ok(!parsed.mcpServers['slack-oauth'], 'stdio 모드에서는 slack-oauth 가 제외되어야 합니다');
  assert.ok(!readProject('.mcp.json').includes('${'), '미치환 플레이스홀더가 남아 있습니다');
});

test('aiw gitignore --check 와 aiw check 가 통과한다', () => {
  const gitignoreResult = aiw(['gitignore', '--check']);
  assert.equal(gitignoreResult.status, 0, `gitignore --check 실패:\n${gitignoreResult.stderr}`);

  const checkResult = aiw(['check']);
  assert.equal(checkResult.status, 0, `check 실패:\n${checkResult.stdout}\n${checkResult.stderr}`);
});

test('base.md drift 를 check 가 감지하고 setup 이 복구한다', () => {
  const baseDocPath = path.join(projectDir, '.ai-workflow', 'docs', 'base.md');
  const original = fs.readFileSync(baseDocPath, 'utf-8');
  fs.writeFileSync(baseDocPath, `${original}\n<!-- 임의 수정 -->\n`);

  const driftResult = aiw(['check']);
  assert.equal(driftResult.status, 1, 'drift 상태인데 check 가 통과했습니다');
  assert.match(driftResult.stderr, /drift/);

  const setupResult = aiw(['setup', 'claude', '--yes']);
  assert.equal(setupResult.status, 0);
  assert.equal(fs.readFileSync(baseDocPath, 'utf-8'), original, 'setup 이 base.md 를 원상 복구해야 합니다');

  const recheck = aiw(['check']);
  assert.equal(recheck.status, 0, `복구 후 check 실패:\n${recheck.stderr}`);
});
